### ISSUE TITLE
RMPolygonAnnotation with interiorPolygons issue

### ISSUE THREAD

**Issue by awedeebawe** [mapbox/DEPRECATED-mapbox-ios-sdk#501] opened 2014-09-09 11:08 UTC
Hello Mapbox :)
I am currently developing WKT parser class with iOS SDK support , but when I create polygon using the following method:

[[RMPolygonAnnotation alloc] initWithMapView:mapView points:outerRingPoints interiorPolygons:arrayWithPolygons];

I get this strange line between the last point of the outer ring and the first point of the inner ring (picture attached). Each polygon separately is fine. So is it a bug in the SDK or I did something wrong?
![img_0107](https://cloud.githubusercontent.com/assets/8670596/4200395/972724a8-3810-11e4-957e-0b27c5640ad4.PNG)

**Comment by incanus** [comment] 2014-09-10 02:17
Are you seeing this on the latest version? There was a recent bug fix for closing internal polygons.

**Comment by mohpor** [comment] 2014-09-10 03:18
That's a problem with polygons @awedeebawe , I have faced it in the past and I have fixed it, the problem is, RMPolygonAnnotation is only able to handle simple polygon (technical term) and what you're trying to draw is a complex polygon. If you are interested in Convex Hulls and such, I have the solution and it needs some extra calculations on your polygon.
Let me know if I could be of any help.

**Comment by awedeebawe** [comment] 2014-09-10 06:04
@mohpor thank you, I'd love to see your solutions.

@incanus I am using the Mapbox.framework file I downloaded a few weeks ago. I will update my files and try again :) Thank you for response though :+1:

**Comment by mohpor** [comment] 2014-09-10 06:09
I had to ask it on SO and with a decent bounty, somebody made a very fine solution for me. I can send you the SO Link and if you could' use it, I can elaborate on that.
Here is the SO link:
[How to simplify a single complex UIBezierPath polygon in iOS](http://stackoverflow.com/questions/23578760/how-to-simplify-a-single-complex-uibezierpath-polygon-in-ios)

Hope this helps,
Cheers

**Comment by awedeebawe** [comment] 2014-09-10 07:43
Close the thread :) I updated my MapBox version and the problem is gone. Thank you, @incanus :)

**Closed as completed** 2014-09-16 00:55 UTC
