### ISSUE TITLE
Map Annotation layers wiggle when moving map

### ISSUE THREAD

**Issue by ryanmaxwell** [mapbox/DEPRECATED-mapbox-ios-sdk#120] opened 2012-09-22 10:39 UTC
I'm not sure if this is a known issue, I've done some searching but can't find much about it. 

I've added several RMAnnotations to a map. Each annotation has a custom UIImage RMMarker via the RMMapView delegate call.

When zoomed in at a high level (>16) you can notice the markers wiggling around on the map as you drag. It's the same behaviour with the user location dot. It just jiggles like it's had too much caffeine.

I'm thinking it may be redrawing of the layer as you pan, and the margin of error in the coordinate causing a slight difference in placement on each redraw?

**Comment by incanus** [comment] 2012-10-01 20:53
This is a dupe of #72. Thanks for the added detail, though.

**Closed as completed by incanus** 2012-10-01 20:53 UTC
