### ISSUE TITLE
iOS 7 error initializing without superview

### ISSUE THREAD

**Issue by cga-F4** [mapbox/DEPRECATED-mapbox-ios-sdk#317] opened 2013-09-30 15:24 UTC
Hi Justin,
I tried the newly arrived iOS 7 branch with my code, and I have a crash during initialization of the mapView.

In my code, I create the RMMapView before adding it as a subview (even before I make the `[self.window makeKeyAndVisible];`). With the new code, I got this error at this line :
`[self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
@"V:[logoBug]-4-|" options:0  metrics:nil views:@{ @"logoBug" : _logoBug }]];` in the `- (void)updateConstraints` method of `RMMapView.m`.

The error logged is 
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse constraint format: 
Unable to interpret '|' character, because the related view doesn't have a superview 
V:[logoBug]-4-| 
               ^'

Knowing that I set `mapView.showLogoBug = NO;`, tell me if you will check this initialization problem or do I need to delay the creation of the mapView ?

**Comment by incanus** [comment] 2013-10-25 19:06
Are you still seeing this in `develop` (which just got `ios7` merged into it)?

**Comment by cga-F4** [comment] 2013-10-28 09:42
Hi Justin,
I tried the develop branch. First I couldn't get the right revision for SMCalloutView (so I took the last revision Subproject commit 8cbde820a1c58d998b31027ca1aa9ecd604f2cf8).
And I still have the problem, in the same function  
 `[viewController.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:formatString
                                                                                        options:0
                                                                                        metrics:@{ @"bottomSpacing" : @(bottomSpacing) }
                                                                                          views:views]];`
Here are the new logs (from XCode 5.0.1) : 

`The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0xc076110 V:[UIImageView:0xc284cc0]-(-476)-[_UILayoutGuide:0xc0758a0]>
    When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2013-10-28 10:34:22.188 Quimper[9518:70b] View hierarchy unprepared for constraint.
    Constraint: <NSLayoutConstraint:0xc076110 V:[UIImageView:0xc284cc0]-(-476)-[_UILayoutGuide:0xc0758a0]>
    Container hierarchy: 
<UIView: 0xc65cbe0; frame = (0 64; 320 416); autoresize = W+H; layer = <CALayer: 0xc65cc40>>
   | MapView at {0,0}-{320x416}
   |    | <RMLoadingTileView: 0xc0683d0; baseClass = UIScrollView; frame = (0 0; 320 416); clipsToBounds = YES; userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0xc068890>; layer = <CALayer: 0xc068610>; contentOffset: {320, 832}>
   |    |    | <UIView: 0xc068bc0; frame = (0 0; 960 1248); layer = <CALayer: 0xc068c20>>
   |    | <RMMapScrollView: 0xc652710; baseClass = UIScrollView; frame = (0 0; 320 416); opaque = NO; gestureRecognizers = <NSArray: 0xc652b90>; layer = <CALayer: 0xc652910>; contentOffset: {2049197, 1457867}>
   |    |    | <UIView: 0xc652e60; frame = (0 0; 4.1943e+06 4.1943e+06); transform = [16384, 0, 0, 16384, 0, 0]; userInteractionEnabled = NO; layer = <CALayer: 0xc652ec0>>
   |    |    |    | <RMMapTiledLayerView: 0xc653070; frame = (0 0; 256 256); opaque = NO; layer = <CATiledLayer: 0xc653140>>
   |    | <RMMapOverlayView: 0xc656f10; frame = (0 0; 320 416); userInteractionEnabled = NO; layer = <CAScrollLayer: 0xc6570d0>>
   |    | <UIView: 0xc289490; frame = (279 5; 36 36); layer = <CALayer: 0xc2894f0>>
   |    |    | <UIButton: 0xc2863a0; frame = (0 0; 36 36); alpha = 0; opaque = NO; layer = <CALayer: 0xc2857e0>>
   |    |    |    | <UIImageView: 0xc65f550; frame = (0 0; 36 36); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0xc65f6c0>>
   |    | <UIView: 0xc289970; frame = (226 396; 89 15); userInteractionEnabled = NO; layer = <CALayer: 0xc2899d0>>
   |    |    | <UIImageView: 0xc28a650; frame = (0 0; 5 15); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0xc28b6f0>>
   |    |    | <UIImageView: 0xc28c140; frame = (5 5; 79 5); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0xc28d410>>
   |    |    | <UIImageView: 0xc28cd70; frame = (84 0; 5 15); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0xc28eb90>>
   |    |    | <UILabel: 0xc28ed40; frame = (27 -10; 35 15); text = '500 m'; clipsToBounds = YES; userInteractionEnabled = NO; layer = <CALayer: 0xc28e4c0>>
   | <_UILayoutGuide: 0xc65f950; frame = (0 0; 0 0); hidden = YES; layer = <CALayer: 0xc65fa40>>
   | <_UILayoutGuide: 0xc0758a0; frame = (0 0; 0 0); hidden = YES; layer = <CALayer: 0xc075910>>
    View not found in container hierarchy: <UIImageView: 0xc284cc0; frame = (8 454; 80 22); opaque = NO; autoresize = RM+TM; userInteractionEnabled = NO; layer = <CALayer: 0xc285b30>>
    That view's superview: NO SUPERVIEW`

**Comment by MrZoidberg** [comment] 2013-11-23 15:04
Hi,

I think I can confirm this issue with the latest sources from the develop branch. Here are my logs:
<code>
The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x14ea5b30 V:[UIImageView:0x14d83e80]-(-499)-[_UILayoutGuide:0x14eaa340]>
    When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2013-11-23 16:59:14.595 ParkovkiUA[7612:60b] View hierarchy unprepared for constraint.
    Constraint: <NSLayoutConstraint:0x14ea5b30 V:[UIImageView:0x14d83e80]-(-499)-[_UILayoutGuide:0x14eaa340]>
    Container hierarchy: 
<UIView: 0x14d83400; frame = (0 0; 320 568); autoresize = W+H; layer = <CALayer: 0x14d83460>>
   | <UIActivityIndicatorView: 0x14d7a6a0; frame = (0 32.5; 0 0); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x14d7a7d0>>
   |    | <UIImageView: 0x14d7abe0; frame = (-19 -19; 37 37); opaque = NO; userInteractionEnabled = NO; animations = { contents=<CAKeyframeAnimation: 0x14d8c160>; }; layer = <CALayer: 0x14d76810>>
   | <UIView: 0x14d818f0; frame = (0 65; 0 0); autoresize = RM+BM; layer = <CALayer: 0x14d81950>>
   |    | MapView at {0,0}-{320x503}
   |    |    | <RMLoadingTileView: 0x14e823b0; baseClass = UIScrollView; frame = (0 0; 320 503); clipsToBounds = YES; userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x14e82a90>; layer = <CALayer: 0x14e82640>; contentOffset: {640, 652}>
   |    |    |    | <UIView: 0x14e82e70; frame = (0 0; 960 1509); layer = <CALayer: 0x14e82ed0>>
   |    |    | <RMMapScrollView: 0x14d7d150; baseClass = UIScrollView; frame = (0 0; 320 503); opaque = NO; gestureRecognizers = <NSArray: 0x14d7c8b0>; layer = <CALayer: 0x14d7cdf0>; contentOffset: {629653, 355341}>
   |    |    |    | <UIView: 0x14d7e280; frame = (0 0; 1.04858e+06 1.04858e+06); transform = [4096, 0, 0, 4096, 0, 0]; userInteractionEnabled = NO; layer = <CALayer: 0x14d7e2e0>>
   |    |    |    |    | <RMMapTiledLayerView: 0x14d7e490; frame = (0 0; 256 256); opaque = NO; layer = <CATiledLayer: 0x14d7e800>>
   |    |    | <RMMapOverlayView: 0x14e8eeb0; frame = (0 0; 320 503); userInteractionEnabled = NO; layer = <CAScrollLayer: 0x14e8f030>>
   |    |    | <UIView: 0x14e97fb0; frame = (279 5; 36 36); layer = <CALayer: 0x14e98010>>
   |    |    |    | <UIButton: 0x14e94630; frame = (0 0; 36 36); alpha = 0; opaque = NO; layer = <CALayer: 0x14e942b0>>
   |    |    |    |    | <UIImageView: 0x14ea7c20; frame = (0 0; 36 36); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x14ea78f0>>
   | <UIToolbar: 0x14d7b8f0; frame = (0 21; 0 0); alpha = 0.9; opaque = NO; autoresize = W+TM; layer = <CALayer: 0x14d7c240>>
   |    | <_UIToolbarBackground: 0x14d7fa00; frame = (0 0; 0 0); autoresize = W; userInteractionEnabled = NO; layer = <CALayer: 0x14d7fb20>>
   |    |    | <_UIBackdropView: 0x14d7fd60; frame = (0 0; 0 0); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <_UIBackdropViewLayer: 0x14d7ff70>>
   |    |    |    | <_UIBackdropEffectView: 0x14d80140; frame = (0 0; 0 0); clipsToBounds = YES; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CABackdropLayer: 0x14d801b0>>
   |    |    |    | <UIView: 0x14d801e0; frame = (0 0; 0 0); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x14d80240>>
   |    | <UIImageView: 0x14d80850; frame = (0 -1; 0 0); autoresize = W+BM; userInteractionEnabled = NO; layer = <CALayer: 0x14d80700>>
   |    | <UIButton: 0x14e475c0; frame = (16 5; 218 33); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; tag = 201; layer = <CALayer: 0x14e6efc0>>
   |    | <UIToolbarButton: 0x14ea90f0; frame = (0 0; 21 0); opaque = NO; layer = <CALayer: 0x14ea9510>>
   |    |    | <_UIToolbarNavigationButton: 0x14ea9600; frame = (0 0; 43 30); opaque = NO; layer = <CALayer: 0x14ea8fa0>>
   | <UIToolbar: 0x14d82700; frame = (0 65; 0 0); clipsToBounds = YES; opaque = NO; autoresize = W+TM; layer = <CALayer: 0x14d827a0>>
   |    | <_UIToolbarBackground: 0x14d828d0; frame = (0 0; 0 0); autoresize = W; userInteractionEnabled = NO; layer = <CALayer: 0x14d82970>>
   |    | <UIImageView: 0x14d82c10; frame = (0 -1; 0 0); autoresize = W+BM; userInteractionEnabled = NO; layer = <CALayer: 0x14d82be0>>
   |    | <UIToolbarButton: 0x14ea8ce0; frame = (0 0; 18 0); opaque = NO; layer = <CALayer: 0x14ea8c90>>
   |    |    | <_UIToolbarNavigationButton: 0x14ea8dd0; frame = (0 0; 40 30); opaque = NO; layer = <CALayer: 0x14ea8ef0>>
   | <_UILayoutGuide: 0x14ea8030; frame = (0 0; 0 64); hidden = YES; layer = <CALayer: 0x14ea8140>>
   | <_UILayoutGuide: 0x14eaa340; frame = (0 65; 0 0); hidden = YES; layer = <CALayer: 0x14eaa270>>
    View not found in container hierarchy: <UIImageView: 0x14d83e80; frame = (8 477; 80 22); opaque = NO; autoresize = RM+TM; userInteractionEnabled = NO; layer = <CALayer: 0x14e94250>>
    That view's superview: NO SUPERVIEW
2013-11-23 16:59:14.602 ParkovkiUA[7612:60b] **\* Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to install constraint on view.  Does the constraint reference something from outside the subtree of the view?  That's illegal. constraint:<NSLayoutConstraint:0x14ea5b30 V:[UIImageView:0x14d83e80]-(-499)-[_UILayoutGuide:0x14eaa340]> view:<UIView: 0x14d83400; frame = (0 0; 320 568); autoresize = W+H; layer = <CALayer: 0x14d83460>>'
</code>

**Comment by MrZoidberg** [comment] 2013-11-28 23:55
This bug reproduces only when `showLogoBug` is set to NO

**Comment by MrZoidberg** [comment] 2014-01-20 15:22
Please take a look at 1cd588119524925f9c2eb1094da06f65223766e9. It seems this commit fixes the issue with showLogoBug = NO and auto layout.

**Comment by dcloud** [comment] 2014-01-28 23:52
:+1:

**Comment by cga-F4** [comment] 2014-02-03 15:00
MrZoidberg's commit solves the crash for me too.

**Comment by mkll** [comment] 2014-02-24 22:12
Still see this in 1.1.0 release.

**Comment by namannik** [comment] 2014-02-25 00:32
I just saw this bug today while incorporating version 1.1.0 into my project.  My dirty workaround is to change a line in RMMapView.m from this:

```
if (_logoBug)
```

to:

```
if (_logoBug && self.showLogoBug)
```

**Comment by incanus** [comment] 2014-02-25 00:36
Sorry, this is fixed as of fd21d75f65862493a4950e36927a1d167c7ce665 in `develop`.

**Closed as completed by incanus** 2014-02-25 00:36 UTC
Labels: bug

**Comment by namannik** [comment] 2014-02-25 01:40
Thanks, Justin.  I've added the `develop` branch to my project, and the crash is gone.

**Comment by nderkach** [comment] 2014-05-26 20:48
This still hasn't been merged into the main branch, why?

**Comment by incanus** [comment] 2014-05-26 20:51
No time for formal release QA and packaging right now. This will be coming soon.
