### ISSUE TITLE
MKGeodesicPolyline equivalent for MapBox

### ISSUE THREAD

**Issue by jeffbailey** [mapbox/DEPRECATED-mapbox-ios-sdk#385] opened 2014-01-28 15:53 UTC
A great feature enhancement would be to support an equivalent to the MKGeodesicPolyline for MapBox.  My use case would be to support a more realistic flight path between two airports.  Has anyone created a custom annotation for this?

**Comment by incanus** [comment] 2014-01-28 18:06
Check out this branch: https://github.com/mapbox/mapbox-ios-sdk/tree/great-circles and `RMGreatCircleAnnotation`.

**Comment by incanus** [comment] 2014-01-28 18:06
Dupe of https://github.com/mapbox/mapbox-ios-sdk/pull/303 which will eventually get merged.

**Closed as completed by incanus** 2014-01-28 18:06 UTC

**Comment by jeffbailey** [comment] 2014-01-29 17:53
Works great!  Thanks for the help.
