### ISSUE TITLE
RMMapView bug on 64 bit iPhone, in oomWithLatitudeLongitudeBoundsSouthWest

### ISSUE THREAD

**Issue by aleksandarj** [mapbox/DEPRECATED-mapbox-ios-sdk#502] opened 2014-09-16 16:17 UTC
I found this bug using version1.2 and haven't tried the newer ones,
so maybe you've already fixed this but anyway.. 

in iOS SDK, for RMMapView, the zoomWithLatitudeLongitudeBoundsSouthWest:northEast:animated:
has a bug for 64 bit devices. It gives the correct size / zoom of the window, but the offset (or center) is not accurate.

For instance, I tried to zoom in to Florida by giving it the south-west and north-east coordinates (double-checked this on google maps), and on 32bit devices my code functions as expected, but on 64 bit devices there is an offset of about 500km to the south-east (it zooms on the north shores in north america).

I went around this problem with an additional setCenterCoordinate after the zoom because it's not animated in my case.

I found an issue on stackoverflow for this, and I think it is the same problem.
http://stackoverflow.com/questions/23396922/mapbox-zoomwithlatitudelongitudeboundssouthwest-not-zooming-to-correct-locatio/25781239#25781239

For given points that should zoom in on UK
SouthWest = (latitude = 49.724355000000003, longitude = -8.7919210000000003)
NorthEast =  (latitude = 59.556961999999999, longitude = 2.102922)
the function returns:
origin: (185130.482481, 6398696.510918) size: (48919.698096, 66653.088655)

and it actually zooms in to France.

**Comment by incanus** [comment] 2014-09-16 19:23
Thanks for this @aleksandarj. Please let me know when you've had a chance to test this on the latest version, though I will try to take a peek soon.

**Comment by mrabenhorst** [comment] 2014-09-22 15:41
I can confirm this problem occurs with the latest version running on iOS8. 

`[mapView zoomWithLatitudeLongitudeBoundsSouthWest:CLLocationCoordinate2DMake(49.724355000000003, -8.7919210000000003) northEast:CLLocationCoordinate2DMake(59.556961999999999, 2.102922) animated:FALSE];`

Sets map's `centerCoordinate` to: (latitude = 84.256141544221066, longitude = -168.60290069127765)

Which is way up in the arctic ocean... so not the same place as @aleksandarj

**Comment by mrabenhorst** [comment] 2014-09-22 15:49
Also, note that I found `setCenterCoordinate:` also is not functioning perfectly either... 

`[mapView setCenterCoordinate:CLLocationCoordinate2DMake(49.724355000000003, -8.7919210000000003) animated:FALSE];`

Sets `centerCoordinate` to (latitude = 49.724940713586335, longitude = -8.7986511650288488)

Which is approximately 0.3 mile in error.

**Comment by incanus** [comment] 2014-09-30 17:34
I am definitely seeing unusual differences between trying to set the same starting center coordinate on: 
- 32-bit iOS 7
- 32-bit iOS 8
- 64-bit anything

**Comment by incanus** [comment] 2014-09-30 18:30
Wondering if this is an autolayout or layout-time issue. Across all above versions, for a given center coordinate, I am getting identical: 
- scroll view `contentSize`
- desired and set scroll view `contentOffset`
- scroll view `zoomScale`

That is, we are dealing with the same geometries and settings, but the map comes out looking different. I'm thinking the `frame` and/or `bounds` is getting changed and affecting things, but it does not appear to be precision-related. 

Also, interestingly, iOS 8 started logging scroll view `contentSize` when only `contentOffset` was logged before (with `NSLog()`).

**Comment by aleksandarj** [comment] 2014-10-01 09:33
I found the following lines in proj_api.h
#define RAD_TO_DEG 57.29577951308232
#define DEG_TO_RAD .0174532925199432958

these constants are used in 
(RMProjectedPoint)coordinateToProjectedPoint:(CLLocationCoordinate2D)aLatLong

wouldn't this be more accurate especially on a 64 bit device ?
#define RAD_TO_DEG 180.f/M_PI
#define DEG_TO_RAD M_PI/180.f

and I'm currently testing if this has anything to do with the problem, and it seems like it's helping a little bit but I can't be sure yet. What do you think ?

**Comment by kriswallsmith** [comment] 2014-10-05 18:25
Disabling "Use Size Classes" on the storyboard fixes the problem for me.

**Comment by mrabenhorst** [comment] 2014-10-06 15:11
I tried disabling "Use Size Classes" on the storyboard and it did not fix it in my test project - error readout is still the same.

**Comment by jaroslavas** [comment] 2014-11-02 19:31
@aleksandarj have to found what's the cause of this bug?

**Comment by aleksandarj** [comment] 2014-11-03 10:38
@jaroslavas  no I haven't, I just used the workaround I described in the first post, setting desired center coordinates after the zoom

**Comment by incanus** [comment] 2014-11-03 22:25
@aleksandarj Thanks for the idea but this didn't affect my use case described in https://github.com/mapbox/mapbox-ios-sdk/issues/502#issuecomment-57351194. I will however consider putting this in & rebuilding the [distributed `libProj4.a`](https://github.com/mapbox/mapbox-ios-sdk/blob/release/Proj4/libProj4.a) since this is indeed more accurate.

**Comment by incanus** [comment] 2014-11-03 22:40
Noting here that the issue I'm seeing — that starting center differs between 32-bit iOS 7, 32-bit iOS 8, and 64-bit — is actually due to trying to set things in `-viewDidLoad`, which is now a no-no in iOS 8 per Apple engineer note [here](https://devforums.apple.com/message/1030685#1030685) and a similar SO comment [here](http://stackoverflow.com/a/26067231/977220). Doing things in `-viewWillAppear:animated:` or later doesn't have a problem. 

The 64-bit nature of this ticket's problem may still be related, but I'm going to go back to @aleksandarj's original `-zoomWithLatitudeLongitudeBoundsSouthWest:northEast:animated:` for testing now.

**Comment by incanus** [comment] 2014-11-03 22:52
Here's my current testing matrix. 

Code: 

``` objc
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];

    // map view setup code here

    [mapView zoomWithLatitudeLongitudeBoundsSouthWest:CLLocationCoordinate2DMake(49.724355000000003, -8.7919210000000003)
                                            northEast:CLLocationCoordinate2DMake(59.556961999999999, 2.102922)
                                             animated:NO];

[...]
```

|  | **iOS 7.1** | **iOS 8.1** |
| :-: | :-: | :-: |
| **iPhone 5** | ![1](https://cloud.githubusercontent.com/assets/17722/4891803/c991a3e8-63ab-11e4-9fd3-2632c9ec11cb.png) | ![2](https://cloud.githubusercontent.com/assets/17722/4891805/ccf9558a-63ab-11e4-9be5-8f44cc3a097a.png) |
| **iPhone 5s** | ![3](https://cloud.githubusercontent.com/assets/17722/4891807/d0e0acac-63ab-11e4-9870-8ad5fbb0bb2e.png) | ![4](https://cloud.githubusercontent.com/assets/17722/4891810/d4a770c8-63ab-11e4-8ac1-22b2b2f5e5ae.png) |

So whatever it is would appear to be an iOS 7 64-bit bug of some sort, which leads me to think that it might be a bug in `UIScrollView`? Still digging though.

**Comment by incanus** [comment] 2014-11-03 23:00
Ok, after moving anywhere later than `-viewWillAppear:`, results are consistently correct across the board. 

Two methods of doing this: 
1. Using `dispatch_after(...` around the `-setZoom...` call to effectively move into a later pass of the run loop. 
2. Moving to `-viewDidAppear:`. 

Because this only happens on iOS 7 64-bit and has a workaround, I'm going to close this as non-critical. This sort of layout-pass-based problem inherent to using `UIScrollView` is going to be obsoleted by future toolkits based on [Mapbox GL](http://mapbox.com/mapbox-gl) so can be more directly addressed.

**Closed as completed by incanus** 2014-11-03 23:00 UTC
Labels: bug

**Comment by wshelley** [comment] 2015-02-25 12:14
I know this is now closed but for those using a Route-Me fork this fixed the problem for me. For some reason there is a problem with the MapView frame during initialisation. Updating the frame based on another view in the ViewDidLoad seemed to fix the problem.
 [self.MainMapView setFrame:self.view.frame];
