### ISSUE TITLE
libProj4 not getting linked by default

### ISSUE THREAD

**Issue by keyz182** [mapbox/DEPRECATED-mapbox-ios-sdk#232] opened 2013-04-09 10:20 UTC
Hi, 

Every time I do 'pod install' or 'pod update' I have to manually put -lProj4 into OTHER_LDFLAGS in Pods/Pods.xcconfig otherwise building fails with linker errors. This is using the 1.0.2 pod.

I'm new to this, so it may be an issue my end, but I don't think it is.

/Kieran

**Comment by keyz182** [comment] 2013-04-11 10:57
If I manually download the podspec file from the CocoaPod Git repo, and change the m.xconfig line to :

```
m.xcconfig = { 'OTHER_LDFLAGS' => '-ObjC -lProj4', 'LIBRARY_SEARCH_PATHS' => '"${PODS_ROOT}/MapBox/Proj4"' }
```

then include that file manually in my Podfile using

```
pod 'MapBox', :podspec => '/Path/To/MapBox.podspec'
```

it works perfectly.

**Comment by incanus** [comment] 2013-04-22 21:21
Closing as dupe of #230.

**Closed as completed by incanus** 2013-04-22 21:21 UTC
Labels: installation
