### ISSUE TITLE
Warning during Database initialization

### ISSUE THREAD

**Issue by migo** [mapbox/DEPRECATED-mapbox-ios-sdk#547] opened 2014-11-28 12:30 UTC
In RMDatabaseCache - configureDBForFirstUse, there is the line:

```
[[db executeQuery:@"PRAGMA cache-size=100"] close];
```

I always get the following error when the database is initialized:

```
DB Error: 1 "near "-": syntax error"
DB Query: PRAGMA cache-size=100
```

It is only logged and does not seem to affect anything.
However, this could probably be fixed easily (perhaps just replace "-" with "_"?).

**Comment by taylortrimble** [comment] 2014-12-31 07:07
This looks like a dupe of #527. You think so @migo?

**Comment by migo** [comment] 2015-01-01 16:15
Yes, seems to be the same error.

**Comment by taylortrimble** [comment] 2015-01-01 16:44
Want to close this then?

**Closed as completed** 2015-01-01 16:47 UTC
